package com.wl.mall.orm.entity;

// Generated 2015-8-4 21:30:39 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String account;
	private String password;
	private String nickName;
	private String headImage;
	private String tel;
	private String address;
	private String detailAddress;
	private String lastLoginIp;
	private String lastLoginRegion;

	public User() {
	}

	public User(String account, String password) {
		this.account = account;
		this.password = password;
	}

	public User(String account, String password, String nickName,
			String headImage, String tel, String address, String detailAddress,
			String lastLoginIp, String lastLoginRegion) {
		this.account = account;
		this.password = password;
		this.nickName = nickName;
		this.headImage = headImage;
		this.tel = tel;
		this.address = address;
		this.detailAddress = detailAddress;
		this.lastLoginIp = lastLoginIp;
		this.lastLoginRegion = lastLoginRegion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account", nullable = false, length = 32)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nick_name", length = 32)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "head_image", length = 64)
	public String getHeadImage() {
		return this.headImage;
	}

	public void setHeadImage(String headImage) {
		this.headImage = headImage;
	}

	@Column(name = "tel", length = 32)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "address", length = 256)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "detail_address", length = 512)
	public String getDetailAddress() {
		return this.detailAddress;
	}

	public void setDetailAddress(String detailAddress) {
		this.detailAddress = detailAddress;
	}

	@Column(name = "last_login_ip", length = 32)
	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	@Column(name = "last_login_region", length = 32)
	public String getLastLoginRegion() {
		return this.lastLoginRegion;
	}

	public void setLastLoginRegion(String lastLoginRegion) {
		this.lastLoginRegion = lastLoginRegion;
	}

}
