# 默认环境
datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;mysqlEncoding=utf8
    userName: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initialPoolSize: 3
    minPoolSize: 2
    maxPoolSize: 50
    acquireIncrement: 3
    idleConnectionTextPeriod: 1800                        
    maxStatements: 100
    numHelperThreads: 10
    maxIdleTime: 60
---
# 开发环境
spring:
    profiles: dev
datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;mysqlEncoding=utf8
    userName: root
    password: 123456
    
---
# 测试环境
spring:
    profiles: test
datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;mysqlEncoding=utf8
    userName: root
    password: 123456

---
# 生产环境
spring:
    profiles: prod
datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_prod?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;mysqlEncoding=utf8
    userName: root
    password: 123456

     