package com.wl.mall.entity;

// default package
// Generated 2015-7-31 15:17:35 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "mall")
public class User implements java.io.Serializable {

	private Long id;
	private String account;
	private String password;
	private String address;
	private String detailAddress;
	private String email;
	private String headImage;
	private String nickName;
	private Date addTime;
	private Date updateTime;
	private String tel;
	private String lastLoginIp;
	private String lastLoginRegion;

	public User() {
	}


	public User(String account, String password, String address,
			String detailAddress, String email, String headImage,
			String nickName, Date addTime, Date updateTime, String tel,
			String lastLoginIp, String lastLoginRegion) {
		this.account = account;
		this.password = password;
		this.address = address;
		this.detailAddress = detailAddress;
		this.email = email;
		this.headImage = headImage;
		this.nickName = nickName;
		this.addTime = addTime;
		this.updateTime = updateTime;
		this.tel = tel;
		this.lastLoginIp = lastLoginIp;
		this.lastLoginRegion = lastLoginRegion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "account", length = 30)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "password", length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "address", nullable = false, length = 40)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "detail_address", nullable = false, length = 65535)
	public String getDetailAddress() {
		return this.detailAddress;
	}

	public void setDetailAddress(String detailAddress) {
		this.detailAddress = detailAddress;
	}

	@Column(name = "email", nullable = false, length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "head_image", nullable = false, length = 50)
	public String getHeadImage() {
		return this.headImage;
	}

	public void setHeadImage(String headImage) {
		this.headImage = headImage;
	}

	@Column(name = "nick_name", nullable = false, length = 20)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", nullable = false, length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "tel", nullable = false, length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "last_login_ip", nullable = false, length = 20)
	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	@Column(name = "last_login_region", nullable = false, length = 20)
	public String getLastLoginRegion() {
		return this.lastLoginRegion;
	}

	public void setLastLoginRegion(String lastLoginRegion) {
		this.lastLoginRegion = lastLoginRegion;
	}

}
